# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: semantic-pull-request
      # You may pin to the exact commit or the version.
      # uses: amannn/action-semantic-pull-request@e682a390b8f9f522ca538b5b5514b8cde08f1857
      uses: amannn/action-semantic-pull-request@v3.5.0
      with:
        # Provide custom types if you don't want the default ones from https://www.conventionalcommits.org
        types: # optional
        # Configure which scopes are allowed.
        scopes: # optional
        # Configure that a scope must always be provided.
        requireScope: # optional
        # Configure additional validation for the subject based on a regex. E.g. '^(?![A-Z]).+$' ensures the subject doesn't start with an uppercase character.
        subjectPattern: # optional
        # If `subjectPattern` is configured, you can use this property to override the default error message that is shown when the pattern doesn't match. The variables `subject` and `title` can be used within the message.
        subjectPatternError: # optional
        # For work-in-progress PRs you can typically use draft pull requests from Github. However, private repositories on the free plan don't have this option and therefore this action allows you to opt-in to using the special '[WIP]' prefix to indicate this state. This will avoid the validation of the PR title and the pull request checks remain pending. Note that a second check will be reported if this is enabled.
        wip: # optional
        # When using "Squash and merge" on a PR with only one commit, GitHub will suggest using that commit message instead of the PR title for the merge commit, and it's easy to commit this by mistake. Enable this option to also validate the commit message for one commit PRs.
        validateSingleCommit: # optional
        # If you use Github Enterprise, you can set this to the URL of your server (e.g. https://github.myorg.com/api/v3)
        githubBaseUrl: # optional
